### ISSUE TITLE
Certificate error on Windows

### ISSUE THREAD

**Issue by Baptou88** [moesaid/FlutterPP_Public#2]
Hello Everyone,

Today I wanted to try to use this new tool, which looked very interesting! However when I wanted to execute this file `[FlutterPP-windows-0.0.6-MS-NS.msix](https://github.com/moesaid/FlutterPP_Public/releases/download/0.0.6/FlutterPP-windows-0.0.6-MS-NS.msix)`, I found myself facing this error:
```This app package’s publisher certificate could not be verified. Contact your system administrator or the app developer to obtain a new app package with verified certificates. The root certificate and all immediate certificates of the signature in the app package must be verified (0x800B010A)```

Cordially Bapt'

**Comment by moesaid** [comment]
Hey buddy that's expect error since we don't have a windows distribution certificate yet. To be able to install please follow the steps in our wiki 

https://github.com/moesaid/FlutterPP_Public/wiki/How-to-Windows

**Comment by Baptou88** [comment]
Thanks !
